using System.Collections.Generic;

public static class BlackJack_Deck
{
    public static List<BlackJack_Card> cards = new List<BlackJack_Card>() {
        new BlackJack_Card("Clubs Ace"),
        new BlackJack_Card("Clubs 2"),
        new BlackJack_Card("Clubs 3"),
        new BlackJack_Card("Clubs 4"),
        new BlackJack_Card("Clubs 5"),
        new BlackJack_Card("Clubs 6"),
        new BlackJack_Card("Clubs 7"),
        new BlackJack_Card("Clubs 8"),
        new BlackJack_Card("Clubs 9"),
        new BlackJack_Card("Clubs 10"),
        new BlackJack_Card("Clubs Jack"),
        new BlackJack_Card("Clubs Queen"),
        new BlackJack_Card("Clubs King"),
        new BlackJack_Card("Diamonds Ace"),
        new BlackJack_Card("Diamonds 2"),
        new BlackJack_Card("Diamonds 3"),
        new BlackJack_Card("Diamonds 4"),
        new BlackJack_Card("Diamonds 5"),
        new BlackJack_Card("Diamonds 6"),
        new BlackJack_Card("Diamonds 7"),
        new BlackJack_Card("Diamonds 8"),
        new BlackJack_Card("Diamonds 9"),
        new BlackJack_Card("Diamonds 10"),
        new BlackJack_Card("Diamonds Jack"),
        new BlackJack_Card("Diamonds Queen"),
        new BlackJack_Card("Diamonds King"),
        new BlackJack_Card("Hearts Ace"),
        new BlackJack_Card("Hearts 2"),
        new BlackJack_Card("Hearts 3"),
        new BlackJack_Card("Hearts 4"),
        new BlackJack_Card("Hearts 5"),
        new BlackJack_Card("Hearts 6"),
        new BlackJack_Card("Hearts 7"),
        new BlackJack_Card("Hearts 8"),
        new BlackJack_Card("Hearts 9"),
        new BlackJack_Card("Hearts 10"),
        new BlackJack_Card("Hearts Jack"),
        new BlackJack_Card("Hearts Queen"),
        new BlackJack_Card("Hearts King"),
        new BlackJack_Card("Spades Ace"),
        new BlackJack_Card("Spades 2"),
        new BlackJack_Card("Spades 3"),
        new BlackJack_Card("Spades 4"),
        new BlackJack_Card("Spades 5"),
        new BlackJack_Card("Spades 6"),
        new BlackJack_Card("Spades 7"),
        new BlackJack_Card("Spades 8"),
        new BlackJack_Card("Spades 9"),
        new BlackJack_Card("Spades 10"),
        new BlackJack_Card("Spades Jack"),
        new BlackJack_Card("Spades Queen"),
        new BlackJack_Card("Spades King")
    };
}
